### ISSUE TITLE
PyTest pegged to version number

### ISSUE THREAD

**Issue by psi29a** [vinitkumar/json2xml#103]
PyTest is currently pegged against 7.0.0rc1

Since other projects make use of poetry, poetry is very strict about handling deps.

Can you set PyTest not to be a dependancy?

It's perfectly fine for testing, but not for a release to production kind of thing.

**Comment by vinitkumar** [comment]
I agree with your reasoning and will be merging your patch for the same.

**Comment by vinitkumar** [comment]
@psi29a Released a new build to pypi

- https://github.com/vinitkumar/json2xml/releases/tag/3.12.0
- https://pypi.org/project/json2xml/3.12.0/

**Comment by psi29a** [comment]
Awesome, thank you!
