### ISSUE TITLE
dicttoxml adds 'b...'

### ISSUE THREAD

**Issue by Jeroendevr** [vinitkumar/json2xml#126]
**Describe the bug**
Using the function json2xml.dicttoxml.dicttoxml

**To Reproduce**
1. Run :
```python
from json2xml.dicttoxml import dicttoxml
obj = {'bike': 'blue'}
xml = dicttoxml(obj=obj ,root=False)
print(xml)
```
2. See: 
```python
b'<bike type="str">blue</bike>'
```

**Expected behavior**
```python
<bike type="str">blue</bike>
```

**Screenshots**
NA

**Desktop (please complete the following information):**
 - OS: [macOS]
 - Python 3.9.12
 - json2xml 3.18.0

**Additional context**
It seems to happen around here:

```python
# dicttoxml.py
# line 445
    if root:
        output.append('<?xml version="1.0" encoding="UTF-8" ?>')
        output_elem = convert(
            obj, ids, attr_type, item_func, cdata, item_wrap, parent=custom_root
        )
        output.append(f"<{custom_root}{namespacestr}>{output_elem}</{custom_root}>")
    else:
-->     output.append( #adds ' '
            convert(obj, ids, attr_type, item_func, cdata, item_wrap, parent="")
        )

--> return "".join(output).encode("utf-8") #adds b 
```

**Comment by vinitkumar** [comment]
The method 'dicttoxml' returns bytes. 
You can always decode it to string `>>> "".join(output).encode("utf-8").decode("utf-8")`

I am not sure if I can do the change without breaking compatibility for other usage of this library.

**Comment by Jeroendevr** [comment]
Ah good to know. What would be a usage to have the function return it as bytes?

**Comment by vinitkumar** [comment]
I think it was probably to not get on the encoding and let user have a say in the decoding it.

**Comment by Jeroendevr** [comment]
I agree, thanks for the explanation
