### ISSUE TITLE
setting the xmlns value

### ISSUE THREAD

**Issue by Jeroendevr** [vinitkumar/json2xml#127]
**Describe the bug**
Currently adjusting the xmlns value is not possible as the it leads to xmlns:xmlns.

**To Reproduce**
1. run
```Python
from json2xml.dicttoxml import dicttoxml

obj = {'bike': 'blue'}
xml_namespace = {
    'xmlns':"http://www.w3.org/1999/xhtml"
    }
wrapper = 'vehicle'
xml = dicttoxml(
    obj=obj,
        custom_root=wrapper,
        attr_type=False,
        xml_namespaces=xml_namespace)
print(xml)
```

2. see 
```Python
<?xml version="1.0" encoding="UTF-8" ?>
<vehicle xmlns:xmlns="http://www.w3.org/1999/xhtml">
<bike>blue</bike>
</vehicle>
```

**Expected behavior**
```Python
<?xml version="1.0" encoding="UTF-8" ?>
<vehicle xmlns="http://www.w3.org/1999/xhtml">
<bike>blue</bike>
</vehicle>
```
**Screenshots**
NA

**Desktop (please complete the following information):**
 - OS: macOS
 - Python : 3.9.12
 - json2xml : 3.18.0

**Additional context**

**Comment by vinitkumar** [comment]
@Jeroendevr All three of your PRs are merged and released to pypi.

However, I would really appreciate and it would be a great value add, if you can document the usage (probably same as how you used the test examples) in the readme as well. This will go a long way in making people understand how we can use namespaces today.

**Comment by Jeroendevr** [comment]
Thanks for approving the PR's. Sure I'll add some docs.📄 I was still doubtful of your opinion on my implementation therefore I didn't write the docs yet. 𝌗
Good to keep the docs up to date! thanks for the reminder, also feel free to remind me if I didn't do it within a month. 😶‍🌫️

**Comment by vinitkumar** [comment]
@Jeroendevr I liked your implementation, hence merged it. Please go ahead with writing docs and I would really appreciate it and merge/release it.

**Comment by vinitkumar** [comment]
> Thanks for approving the PR's. Sure I'll add some docs.📄 I was still doubtful of your opinion on my implementation therefore I didn't write the docs yet. 𝌗
> Good to keep the docs up to date! thanks for the reminder, also feel free to remind me if I didn't do it within a month. 😶‍🌫️

If you have sometime, please send that PR. Would love to merge it.
