### ISSUE TITLE
Installed but doesn't work.

### ISSUE THREAD

**Issue by ryosa** [vinitkumar/json2xml#13]
> [root ~]# python -m json2xml.cli ./test.json
> /usr/bin/python: No module named json2xml.cli
> ## [root ~]# pip show json2xml
> 
> Metadata-Version: 1.0
> Name: json2xml
> Version: 1.1.0
> Summary: To covert json data to xml data
> Home-page: http://github.com:vinitkumar/json2xml.git
> Author: Vinit Kumar
> Author-email: vinit.kumar@changer.nl
> License: UNKNOWN
> Location: /usr/lib/python2.7/site-packages
> Requires: BeautifulSoup4, dict2xml, simplejson, six, requests
> Classifiers:

What's wrong?

**Comment by vinitkumar** [comment]
@ryosa Will and reproduce and let you know. Are you testing on Python3.

**Comment by ryosa** [comment]
@vinitkumar Thanks. I'm using Python2 on CentOS 7.2.

[root ~]# ls -ls /usr/lib/python2.7/site-packages/json2xml
4 -rw-r--r-- 1 root root   18  9月 30 14:21 __init__.py
4 -rw-r--r-- 1 root root  171  9月 30 14:21 __init__.pyc
4 -rw-r--r-- 1 root root 1640  9月 30 14:21 json2xml.py
4 -rw-r--r-- 1 root root 1592  9月 30 14:21 json2xml.pyc

**Comment by vinitkumar** [comment]
Fixed in the latest master.
