### ISSUE TITLE
Logging should be disabled by default

### ISSUE THREAD

**Issue by ricciarellif** [vinitkumar/json2xml#130]
Using your library inside another project *which makes use of  its own logging* results in a mix of messages: your library ones and theose of the project that makes use of your library.

**Expected behavior**
The library SHOULDN'T log anything: eventually, a parameter could be provided to enable the logging of your library

**Desktop (please complete the following information):**
 - OS: Linux Manjaro, LATEST
 - Browser Chrome, Firefox, Opera, Falkon
 - Version LATEST

**Comment by vinitkumar** [comment]
@ricciarellif I agree with your sentiment. I will implement this in the latest release.

**Comment by ricciarellif** [comment]
Many thanks Kumar, I appreciate it a lot. 
Best regards and keep up your great job.

**Comment by vinitkumar** [comment]
Implemented the fix in https://github.com/vinitkumar/json2xml/pull/131

Please check the master branch in your code and see if this is what you expect. I think all your complains should be gone now.

**Comment by vinitkumar** [comment]
We have removed the logging by default in the latest release, please check.
