### ISSUE TITLE
dicttoxml: recursive array broken since json2xml 3.19.0

### ISSUE THREAD

**Issue by DirkRichter** [vinitkumar/json2xml#151]
Sample
`dicttoxml.dicttoxml([{'x':[1]}], root=False, attr_type=False)`

**correct result in 3.18.x and before**
`<item><x><item>1</item></x></item>`

**wrong result since 3.19.x**
`<item><item>1</item></item>`

Problem: missing x-element (keyname in dict); no effect toggling list_headers=True/False

Reason seems to be **Repeat list headers** from https://github.com/vinitkumar/json2xml/pull/138

**Comment by DirkRichter** [comment]
mistake

**Comment by vinitkumar** [comment]
Thanks for spotting and contributing a fix for this. It has been merged, tagged and released.

https://pypi.org/project/json2xml/3.19.5/
