### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by dell25** [vinitkumar/json2xml#19]
After running the code like 

> python -m src.cli --url="https://coderwall.com/vinitcool76.json"

I'm getting the next error, but it exports the file. I think that the file is complete. I'm posting this just to be sure.

`Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/lib/python2.7/dist-packages/src/cli.py", line 4, in <module>
    from src.json2xml import Json2xml
  File "/usr/local/lib/python2.7/dist-packages/src/json2xml.py", line 23
    def __init__(self, data: str) -> None:
                           ^
SyntaxError: invalid syntax
`

**Comment by vinitkumar** [comment]
Hi, it looks like you are using Python2. In the code, I have used "Type Annotation", It is only Python3 at the moment. Could you please try it again in Python3. It should just work then.

**Comment by vinitkumar** [comment]
Only python3 is supported, please try with the latest Python3 and it should just work.
