### ISSUE TITLE
Case sensitivity is not kept during conversion

### ISSUE THREAD

**Issue by llitz** [vinitkumar/json2xml#20]
Converting json files to xml files loses case sensitivity. This can be perceived as not only doing a transformation but actually modifying the content.

**Comment by llitz** [comment]
Is there any reason to use BeautifulSoap? I tested a quick program only using dict2xml and the case was not changed.

**Comment by vinitkumar** [comment]
@llitz I was not aware of this bug. Thanks for finding out the bug. Also, I use Beautifulsoup as it was very easy to work with it. It would be awesome if you could contribute a failing test case with this issue as well. I would pick this issue up. Thanks!

**Comment by vinitkumar** [comment]
This is fixed with the latest release too:

For e.g:

```sh
python -m src.cli --data '{"records":[{"Val1": "test","val2":"test"},{"val1": "test2","val2":"test2"}]}'      
```

```xml
<all>
  <records>
    <Val1>test</Val1>
    <val2>test</val2>
  </records>
  <records>
    <val1>test2</val1>
    <val2>test2</val2>
  </records>
</all>
```

**Comment by vinitkumar** [comment]
This one is fixed in the latest release too:

```sh
 python -m src.cli --data '{"records":[{"Val1": "test","val2":"test"},{"val1": "test2","val2":"test2"}]}'       
```

```xml
<all>
  <records>
    <Val1>test</Val1>
    <val2>test</val2>
  </records>
  <records>
    <val1>test2</val1>
    <val2>test2</val2>
  </records>
</all>
```
