### ISSUE TITLE
json with multiple records generates invalid XML

### ISSUE THREAD

**Issue by llitz** [vinitkumar/json2xml#21]
A json file with multiple entries is creating an invalid file:

{"records":[{"val1": "test","val2":"test"},{"val1": "test2","val2":"test2"}]}

It creates two records tag not belonging to any other tag.

When printing straight from dict2xml, it is possible to use the flag "wrap=all" to handle cases like this (You can also pass an argument to prettify and get rid of Beautifulsoap)

**Comment by vinitkumar** [comment]
@llitz Thanks for pointing out the bug. There are test cases in the code, could you please contribute a failing test for this?
