### ISSUE TITLE
64bit Package

### ISSUE THREAD

**Issue by gismcieri** [vinitkumar/json2xml#24]
Hi is json2xml only a 32bit package or is a 64bit package available

**Comment by vinitkumar** [comment]
Hi @gismcieri If you are windows you can easily build a 32 or 64 bit package using this:

https://docs.python.org/2/distutils/builtdist.html#cross-compiling-on-windows

**Comment by gismcieri** [comment]
Thank you. 

I will give that a try soon.  I just set up a 32bit python 3.6 in Anaconda for testing.

Matt
