### ISSUE TITLE
how to remove <all></all> tag

### ISSUE THREAD

**Issue by ts-kazuo-ieiri** [vinitkumar/json2xml#29]
how to remove \<all\>\</all\>  tag?

**Comment by vinitkumar** [comment]
Hi @ts-kazuo-ieiri, I think `all` come from this line of the code. 
https://github.com/vinitkumar/json2xml/blob/master/src/json2xml.py#L83

You can remove `all` from wrap and check, it should just work.

```python
 return dict2xml.dict2xml(self.data, wrap="", indent="  ")
```

I think it would just work. Let me know if it doesn't

**Comment by ts-kazuo-ieiri** [comment]
Hi @vinitkumar , you are right. it removes all the \<all\>\</all\> tag as you said.

```python
#return dict2xml.dict2xml(self.data, wrap="all", indent="  ")
return dict2xml.dict2xml(self.data, indent="  ")
```
Thank you!
