### ISSUE TITLE
remove parameters from end tag

### ISSUE THREAD

**Issue by ts-kazuo-ieiri** [vinitkumar/json2xml#30]
if a tag has parameter like below end tag also has the prameter and tag name and parameter is merged by underscore.

**json**
`'methodName version="1.0"' : 'XXXXXXXXXXXXXXXXXXXXXXX'`

**xml**
`<methodName_version_"1.0">XXXXXXXXXXXXXXXXXXXXXXX</methodName_version_1.0>
`

how can it be like this?
**xml**
`<methodName version="1.0">XXXXXXXXXXXXXXXXXXXXXXX</methodName>`

**Comment by vinitkumar** [comment]
Could you post a JSON that you are trying to convert to XML. It could help me debug this. Honestly, I never came across this issue before so I might have to look into it.

**Comment by vinitkumar** [comment]
@ts-kazuo-ieiri It doesn't look like a json object but a dict, I had to clean it up and use json.dumps(dict_object) to get something like this:


```json
{
    "methodCall": {
        "methodName version='1.0'": "XXXXXXXXXXXXXXXXXXXXXXX", 
        "params": {
            "param": [
                {"name": "REGISTE_DATE", "value": "2018/5/28 0:01"}, 
                {"name": "SEX", "value": 1}, 
                {"name": "TEL1", "value": 244985344}, 
                {"name": "TEL2", "value": 0}, 
                {"name": "EMAIL", "value": "Masayuki_Miyasaka@jexgoc.ac.bdl"}, 
                {"name": "POST_CD", "value": "969-6223"}, 
                {"name": "ADDRESS", "value": "fukushimaken oonumagunaizumisatomachi asahiterairi"}, 
                {"name": "NAME1", "value": "Oosaki Matsuo"}
            ]
        }
    }
}
```

Also, I had to clean this by hand after doing json.dumps for this object.

`"methodName version=\\"1.0\\"": "XXXXXXXXXXXXXXXXXXXXXXX",`

**Comment by ts-kazuo-ieiri** [comment]
@vinitkumar I checked that after executed json.dumps(dict_object), the json data can be set like this.
`req = requests.post(url, data=json_data)`
I don't have problem with end tag and parameter has been set correctly. 

Thank you!

**Comment by vinitkumar** [comment]
@ts-kazuo-ieiri Okay, if you think your issue has been resolved then please close the ticket.

**Comment by ts-kazuo-ieiri** [comment]
@vinitkumar Yes this issue has been fixed. thank you so much.
