### ISSUE TITLE
how to save the xml(type:str) into a .xml file

### ISSUE THREAD

**Issue by shenhongcai** [vinitkumar/json2xml#33]

**Comment by vinitkumar** [comment]
Hi @shenhongcai. Please correct me if I am wrong, but you want to save the XML output to a xml file.

For this as per the example, try and do something like this:


`python -m src.cli --file="examples/example.json" > example.xml`

Now, the output would be saved in example.xml file. Let me know if this solves your issue.

**Comment by lpengxue** [comment]
@vinitkumar The output would be saved in example.xml file. You are right.
