### ISSUE TITLE
Output "<class 'dict'>" after every readfromjson()

### ISSUE THREAD

**Issue by abgrac** [vinitkumar/json2xml#44]
Hi!

I don't know if this is a real issue, but from version 2.2.1 to 3.0.0, after every readfromjson() call, the console prints "<class 'dict'>" (assuming type(returnVar));

The line below represents my code:
jData = readfromjson("\\\\localhost\\POS_JOGO\\AutoUpdaterBRAsB.json")

**Comment by vinitkumar** [comment]
@abgrac Thanks for reporting this issue.

Well, it is not really a issue but there was a leftover print statement while debugging and it's job was to just print the type of the data type which was `<class 'dict'>`. I removed that and pushed a new release under v3.0.1 for this. Please upgrade from the pypi and that should be gone.

Also, please refer to the doc in the readme about the usage. https://github.com/vinitkumar/json2xml#usage
