### ISSUE TITLE
Attribute support

### ISSUE THREAD

**Issue by de0xyrib0se** [vinitkumar/json2xml#45]
Is there any attribute support? XML almost always contains them.

**Comment by vinitkumar** [comment]
@de0xyrib0se Thanks for reporting this issue. It looks like using something like https://github.com/quandyfactory/dicttoxml Would be a better choice. It is more feature reach and supports attribute and other features as well. I will implement it once I find the time.

**Comment by vinitkumar** [comment]
@de0xyrib0se Good news, the feature is completed. Check out this branch and let me know if you like it? https://github.com/vinitkumar/json2xml/pull/47
