### ISSUE TITLE
json2xml should support adding namespaces

### ISSUE THREAD

**Issue by userlerueda** [vinitkumar/json2xml#46]
**Is your feature request related to a problem? Please describe.**
Today json2xml does not allow you to read the namespaces as created from xml2dict

**Describe the solution you'd like**
I would like to see namespaces also part of xml tags

**Describe alternatives you've considered**
Adding namespaces manually

**Additional context**
https://pypi.org/project/xmltodict/

**Comment by vinitkumar** [comment]
@userlerueda Thanks for reporting this issue. This looks like a bit difficult to implement at this moment because the underlying library (dict2xml) doesn't support it. The library you suggest does the reverse of what this library does(instead of dict2xml, it does xml2dict. Also, that library is much better maintained and feature-rich. Let me see if there is a good solution for this.

**Comment by MrBenGriffin** [comment]
I would second adding a custom namespace to json2xml. We would really appreciate it.

**Comment by ankur0101** [comment]
using `wrapper="data:insights"` throws an error

**Comment by vinitkumar** [comment]
> using `wrapper="data:insights"` throws an error

@ankur0101 Please attach the crash logs as well.

**Comment by vinitkumar** [comment]
Thanks for the tip @MrBenGriffin.  A bit late response from my side, but I think I can get this implemented since I run a forked version of dicttoxml in  the project so can adapt the  changes from this. https://github.com/watzon/xmler/blob/master/xmler.py

**Comment by vinitkumar** [comment]
NOTE to self: This might  take a deep-dive into both of the codebases and see how I can implement  the functionality  in a preferably non-breaking way.

**Comment by MrBenGriffin** [comment]
> NOTE to self: This might take a deep-dive i…

I’m not sure if there is a good xml schema loader available - but passing an xsd over as a parameter would allow for both namespaces and also the ability to match attribute names and element names.

**Comment by vinitkumar** [comment]
@MrBenGriffin Would really appreciate if you can post some example for this and how would you like the API to behave?

**Comment by MrBenGriffin** [comment]
> @MrBenGriffin Would really appreciate if you can post some example for this and how would you like the API to behave?

Here is an XSD to XML project - (3 files or so, not my work)
https://github.com/fortesp/xsd2xml

I’m sort of imagining that there’s a degree of coercion going on - and with an xsd there could be a fail (where the json structure doesn’t meet the xsd requirement).  

I could possibly work something up but my diary is very full atm. I’m grateful for this project as is- it’s great for dealing with systems that don’t know json.

**Comment by MrBenGriffin** [comment]
https://pypi.org/project/xsdata/   This may already do everything. - Maybe worth looking at?

**Comment by vinitkumar** [comment]
@MrBenGriffin Thanks, will  look into these and see what I can learn and adopt from them.

**Comment by MrBenGriffin** [comment]
Hey there!  So I've got a simple roundtrip example - the earlier links I sent were not as useful as they could have been..

Here's a tiny example of how XMLSchema does it (with the two xml/xsd file examples).
In fairness, it should be possible for us to implement our requirements using xmlschema - but since we are talking about it, and you have the json2xml repo - maybe it's of value / worth implementing anyhow.

```python3
import xmlschema

schema_xsd = open('sample.xsd').read()
my_schema = xmlschema.XMLSchema(schema_xsd, build=True)
sample_as_json = xmlschema.to_json('sample.xml', schema=my_schema, preserve_root=True)
json_back_to_xml = xmlschema.from_json(sample_as_json, schema=my_schema, preserve_root=True, namespaces={'': 'http://www.sample.org/po'})
xml_as_string = xmlschema.etree_tostring(json_back_to_xml)
print(sample_as_json)
print(xml_as_string)

```

Schema file "example.xsd"
```xsd
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:p="http://www.sample.org/po"
	targetNamespace="http://www.sample.org/po" elementFormDefault="qualified"
	attributeFormDefault="unqualified">
  <xsd:element name="purchaseOrder" type="p:PurchaseOrderType" />
  <xsd:element name="comment" type="xsd:string" />
  <xsd:complexType name="PurchaseOrderType">
    <xsd:sequence>
      <xsd:element name="shipTo" type="p:USAddress">
        <xsd:annotation>
          <xsd:documentation>
            Shipping Address
          </xsd:documentation>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="billTo" type="p:USAddress">
        <xsd:annotation>
          <xsd:documentation>
            Billing Address
          </xsd:documentation>
        </xsd:annotation>
      </xsd:element>
      <xsd:element ref="p:comment" minOccurs="0" />
      <xsd:element name="items" type="p:Items" />
    </xsd:sequence>
    <xsd:attribute name="orderDate" type="xsd:date" />
  </xsd:complexType>
  <xsd:complexType name="USAddress">
    <xsd:sequence>
      <xsd:element name="name" type="xsd:string" />
      <xsd:element name="street" type="xsd:string" />
      <xsd:element name="city" type="xsd:string" />
      <xsd:element name="state" type="xsd:string" />
      <xsd:element name="zip" type="xsd:decimal" />
    </xsd:sequence>
  </xsd:complexType>
  <xsd:complexType name="Items">
    <xsd:sequence>
      <xsd:element name="item" minOccurs="0" maxOccurs="unbounded">
        <xsd:complexType>
          <xsd:sequence>
            <xsd:element name="productName" type="xsd:string" />
            <xsd:element name="quantity">
              <xsd:simpleType>
                <xsd:restriction base="xsd:positiveInteger">
                  <xsd:maxExclusive value="100" />
                </xsd:restriction>
              </xsd:simpleType>
            </xsd:element>
            <xsd:element name="USPrice" type="xsd:decimal">
              <xsd:annotation>
                <xsd:documentation>
                  Price amount in USD
                </xsd:documentation>
              </xsd:annotation>
            </xsd:element>
            <xsd:element ref="p:comment" minOccurs="0" />
            <xsd:element name="shipDate" type="xsd:date" minOccurs="0" />
          </xsd:sequence>
          <xsd:attribute name="partNum" type="p:SKU" use="required">
            <xsd:annotation>
              <xsd:documentation>
                Stock Keeping Unit
              </xsd:documentation>
            </xsd:annotation>
          </xsd:attribute>
        </xsd:complexType>
      </xsd:element>
    </xsd:sequence>
  </xsd:complexType>
  <!-- Stock Keeping Unit, a code for identifying products -->
  <xsd:simpleType name="SKU">
    <xsd:restriction base="xsd:string">
      <xsd:pattern value="\d{3}-[A-Z]{2}" />
    </xsd:restriction>
  </xsd:simpleType>
</xsd:schema>
```

XML file "example.xml"
```xml
<?xml version="1.0" ?>
<purchaseOrder orderDate="1999-10-20" xmlns="http://www.sample.org/po">
  <shipTo>
    <name>Alice Smith</name>
    <street>123 Maple Street</street>
    <city>Mill Valley</city>
    <state>CA</state>
    <zip>90952</zip>
  </shipTo>
  <billTo>
    <name>Robert Smith</name>
    <street>8 Oak Avenue</street>
    <city>Old Town</city>
    <state>PA</state>
    <zip>95819</zip>
  </billTo>
  <comment>Hurry, my lawn is going wild!</comment>
  <items>
    <item partNum="872-AA">
      <productName>Lawnmower</productName>
      <quantity>1</quantity>
      <USPrice>148.95</USPrice>
      <comment>Confirm this is electric</comment>
    </item>
    <item partNum="926-AA">
      <productName>Baby Monitor</productName>
      <quantity>1</quantity>
      <USPrice>39.98</USPrice>
      <shipDate>1999-05-21</shipDate>
    </item>
  </items>
</purchaseOrder>
```

**Comment by Jeroendevr** [comment]
Is there any status on this feature? Otherwise I am willing to look into this functionality. I would love to have an output like:

```xml
<all xmlns="http://yourwebsitehere">
```

**Comment by vinitkumar** [comment]
@Jeroendevr Sadly, didn't find time to do it yet.

However, if you can implement it in a backward compatible way, I will be more than happy to review and merge it.

**Comment by Jeroendevr** [comment]
Ok, ill give it a try.

**Comment by vinitkumar** [comment]
> Ok, ill give it a try.

@Jeroendevr Any progress on this? Otherwise, I will pick up this ticket myself.

**Comment by Jeroendevr** [comment]
No progress atm, was looking into xml schema but couldn’t figure out the logic yet. 
if you want to pick up. Please go ahead!🚀 please push it to a branch so perhaps I can improve / watch the progress.

**Comment by vinitkumar** [comment]
> No progress atm, was looking into xml schema but couldn’t figure out the logic yet.
> if you want to pick up. Please go ahead!🚀 please push it to a branch so perhaps I can improve / watch the progress.

Thanks for giving it a try. 

Alright, I will pick it up in a branch and also make you a reviewer of that Pull Request, You can question/comment on it if you are unclear about something I did.

**Comment by MrBenGriffin** [comment]
I don't know if it helps you or not, but in the end I didn't use this (json2xml) library - instead favouring xmlschema which supports namespaces. However, it does require that you have (or author)  a schema for the namespace declarations.

**Comment by vinitkumar** [comment]
@MrBenGriffin Thanks for the information, I noticed it about xmlschema too. If I end up adding the support for it, it will be done in a backward compatible way and probably in a similar approach as xmlschema.

**Comment by vinitkumar** [comment]
@userlerueda In the latest release, the dictoxml in this project has support for namespace, please check that out and let me know if that work well enough for you.

**Comment by vinitkumar** [comment]
The functionality is implemented in the latest release. Please check.
