### ISSUE TITLE
pip installed version of json2xml doesn't include to_xml() nor Json2xml class

### ISSUE THREAD

**Issue by sinjihn** [vinitkumar/json2xml#51]
```
$ pip list | grep json
json2xml                  3.0.1     
jsonschema                2.6.0  

$ python
...
>>> import json2xml
>>> dir(json2xml)
['__author__', '__builtins__', '__cached__', '__doc__', '__email__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '__version__', 'readfromjson', 'readfromstring', 'readfromurl', 'utils']
>>> json2xml.__version__
'3.0.0'     
>>>exit()

$ pip install --upgrade json2xml
Requirement already up-to-date: json2xml in /Users/sinjihn/VirtualEnvironments/python3_venv/lib/python3.7/site-packages (3.0.1)
```

Looks like the version of json2xml that gets installed via pip is an older version or missing something?

**Comment by vinitkumar** [comment]
@sinjihn You are right. there seems to be some issues with the version uploaded the the code here. I will fix it tonight. Thanks for reporting.

**Comment by vinitkumar** [comment]
@sinjihn Once again thanks for reporting this issue. I faced this issue before and fixed it once but seems like it was not fixed properly. I have released a proper version on pypi and have also updated the docs accordingly. I hope it works perfectly for you this time. Please check https://pypi.python.org/pypi/json2xml

Using `pip install json2xml --upgrade --no-cache` should get you the latest and the version `3.3.2` must be installed. 
If all works well for you, please close this ticket or if you have any other issue, feel free to comment again or reopen the ticket.

**Comment by sinjihn** [comment]
@vinitkumar thanks for addressing the issue! I can confirm it works properly now. I would suggest, however, making it slightly more intuitive when just doing `import json2xml` such that the utils / the class is accessible that way too.
