### ISSUE TITLE
Usage example syntax issue

### ISSUE THREAD

**Issue by fwbam** [vinitkumar/json2xml#52]
**Describe the bug**
On https://pypi.org/project/json2xml/ The usage example has an error in it. Second from should be import.

`...
from json2xml.utils from readfromurl, readfromstring, readfromjson
...`
should be
`
...
from json2xml.utils import readfromurl, readfromstring, readfromjson
...`

**Comment by Marx1st** [comment]
Thanks! You're a lifesaver! :)

**Comment by vinitkumar** [comment]
cc @fwbam @Marx1st Sorry for the trouble Fixed it in the latest release. 

https://github.com/vinitkumar/json2xml/releases/tag/v3.3.3
https://pypi.org/project/json2xml/3.3.3/

Please upgrade and it should be fixed there.
