### ISSUE TITLE
Bad Json format

### ISSUE THREAD

**Issue by Cabewill** [vinitkumar/json2xml#53]
**Describe the bug**
When trying to read from a json file, that contains a bad json format the library craches the python program

**To Reproduce**
1. Try to import a bad json file
2. Use json2xml.utils readfromjson

**Expected behavior**
I expected that the library raise an exception to be handled in my the python module

**Comment by vinitkumar** [comment]
@Cabewill Please add the bad json file in this issue. I will look into it.

**Comment by Cabewill** [comment]
I will close this issue.
In the function readfromjson you use
` except IOError as exp:`
`        print(exp)`
 `       sys.exit(exp)`

So I don't receive a exception that could be caught with the
`except Exception as e:`
I thought you were handling in the wrong way, but I discover that if I use only
`except` I can get this exception. 
In my opinion you are not using the best way, it would be better if the user get the raw exception, so the user could manage better what to do with it.

I'm closing because it's not a bug, but I strongly suggest you to change this exception treatment.
