### ISSUE TITLE
Attr Type Remove

### ISSUE THREAD

**Issue by bhavesh95863** [vinitkumar/json2xml#54]
Hello
I  tried to convert JSON into XML and it's work fine but it comes with type="str". is there any way to ignore this attribute?

**Comment by vinitkumar** [comment]
Hi, @bhavesh95863 Sorry for the late reply. Sadly there is no such way to ignore the type attribute for now.

**Comment by vinitkumar** [comment]
@bhavesh95863 Please update to the latest version of json2xml. We have the facility to disable types from showing up on the XML.

**Comment by Akhi1** [comment]
can you please let us know how to remove the type attribute? any specific function call?

**Comment by Akhi1** [comment]
> can you please let us know how to remove the type attribute? any specific function call?

yeah got it, here is a snippet for those who are looking for help
`json2xml.Json2xml(data, attr_type=False).to_xml()`
