### ISSUE TITLE
Library ends program execution upon error instead of throwing exception

### ISSUE THREAD

**Issue by lukemat-clear** [vinitkumar/json2xml#64]
**Describe the bug**
When the code in utils.py encounters an error it just stops the program execution instead of throwing an exception or printing an error like standard libraries do.

**To Reproduce**
1. Pass an invalid or incorrectly formatted JSON file to any function in utils.py (e.g. readfromstring, readfromjson)
2. The program will stop running completely.=

**Expected behavior**
When an error or exception is encountered, throw an exception for the caller to catch instead of exiting the program.

**Desktop (please complete the following information):**
N/A - irrelevant

**Comment by vinitkumar** [comment]
@lukemat-clear Thanks for this issue. Upon thinking more on this, I think you are right, It should rather throw an exception instead of halting the program execution.

**Comment by vinitkumar** [comment]
@lukemat-clear https://github.com/vinitkumar/json2xml/commit/1a0e782afa445d5287b8e686cf7eb42aa6d11458
