### ISSUE TITLE
Replace dicttoxml as it is no longer maintained. Last commit is from 2016. 

### ISSUE THREAD

**Issue by oponcea-dn** [vinitkumar/json2xml#69]
**Is your feature request related to a problem? Please describe.**
Replace dicttoxml as it is no longer maintained. Last commit is from 2016. 

**Describe the solution you'd like**
Any library that supports attributes as https://github.com/quandyfactory/dicttoxml/pull/66 is not merged.

**Describe alternatives you've considered**
https://github.com/mbj4668/pyang/blob/master/bin/json2xml

**Comment by vinitkumar** [comment]
@oponcea-dn Thanks for filing a ticket. Let me see what I can do about it.

**Comment by vinitkumar** [comment]
Hi @oponcea-dn. Are you sure you wanted to open a ticket in this repo? I am sure the development has slowed down in the dicttoxml repo, but it just works for me and removing it means writing that code myself or finding a suitable alternative (please suggest if you know any).

**Comment by oponcea-dn** [comment]
Hi @vinitkumar, thanks for answering and I apologize for not updating this issue earlier. So, looking more over the code of Ansible, it is actually NOT using this library but it is calling the "json2xml" command of pyang so you can reject my suggestion.

As an alternative, if you have time, maybe you can adapt the code from pyang to the interface of this library: https://github.com/mbj4668/pyang/blob/master/bin/json2xml ... it has a different licencing (BSD 3 clause) but should be ok if you grab the file and the licence.

**Comment by vinitkumar** [comment]
@oponcea-dn You were right, the code for dict2xml is old, unmaintained and messy. I have forked it, and it is in development now. You are welcome to test this branch out.

**Comment by vinitkumar** [comment]
The forked version of the dicttoxml is mergd with the latest beta release. https://twitter.com/vinitkme/status/1380867675719540740
