### ISSUE TITLE
Typo in import statement?

### ISSUE THREAD

**Issue by pdurusau** [vinitkumar/json2xml#7]
The import statement now reads: 

from src.json2xml import Json2xml

After installing, I had to change to:

from json2xml.json2xml import Json2xml

In order for the script to work. Can you confirm?

**Comment by vinitkumar** [comment]
@pdurusau Yes. There is a typo in readme. Thanks for notifying. I will do a fix asap. You can also send me a pull request.

**Comment by vinitkumar** [comment]
This is fixed in latest master.
