### ISSUE TITLE
dicttoxml ignores the root param

### ISSUE THREAD

**Issue by psi29a** [vinitkumar/json2xml#99]
Code snippit: 
```
from jsontoxml import dicttoxml
payload={'mock': 'payload'}
result = dicttoxml(payload, attr_type=False, root=False)
print(result)
```

Result:
```
b'<?xml version="1.0" encoding="UTF-8" ?><root><mock>payload</mock></root>'
```

What it should look like:
```
b'<mock>payload</mock>'
```

**Comment by psi29a** [comment]
Would be nice to have this in a new stable release since it can be used as a drop-in replacement for dicttoxml once this has been resolved. :)

**Comment by vinitkumar** [comment]
@psi29a Thanks for your contribution. 

I released a new stable version on pypi. https://pypi.org/project/json2xml/3.10.0/

The release notes are here. https://github.com/vinitkumar/json2xml/releases/tag/3.10.0

**Comment by psi29a** [comment]
Brilliant, thank you! :). 

I guess I know what I'll be doing the coming days. 

Cheers!
